#!/bin/bash

if [ ! -f rpmforge-release-0.5.3-1.el6.rf.i686.rpm ]; then

  #i386
  wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.i686.rpm

  #x86_64
  #wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

  wget http://dag.wieers.com/rpm/packages/RPM-GPG-KEY.dag.txt
  rpm --import RPM-GPG-KEY.dag.txt

  #i386
  rpm -Uvh rpmforge-release-0.5.3-1.el6.rf.i686.rpm

  #x86_64
  #rpm -Uvh rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

  yum update 
  yum upgrade -y
fi
2. Installing the packages

#!/bin/bash

# Installing Apache2 + PHP
yum -y install httpd php php-mysql php-gd

# Installing GD modules
yum -y install gd fontconfig-devel libjpeg-devel libpng-devel gd-devel perl-GD

# Installing MySQL
yum -y install openssl-devel perl-DBD-MySQL mysql-server mysql-devel

# Installing PHP Dependencies
yum -y install php-ldap php-xml php-mbstring

# Installing DBI modules
yum -y install perl-DBI perl-DBD-MySQL

# Installing PERL modules
yum -y install perl-Config-IniFiles

# Installing RRDTools
yum -y install rrdtool perl-rrdtool

# Installing Mail
yum -y mail

# Installing SNMP
yum -y install perl-Crypt-DES perl-Digest-SHA1 perl-Digest-HMAC net-snmp-utils
yum -y install perl-Socket6 perl-IO-Socket-INET6 net-snmp net-snmp-libs php-snmp dmidecode lm_sensors perl-Net-SNMP net-snmp-perl

# Misc
yum -y install fping cpp gcc gcc-c++ libstdc++ glib2-devel
# Make is not included on cent-os by default
yum -y install make

# PEAR
yum -y install php-pear
pear channel-update pear.php.net 
# for those who have a web proxy
# pear config-set http_proxy http://my_proxy.com:port 
pear upgrade-all

yum -y install fping openssl-devel openldap-devel postgresql-devel radiusclient-ng-devel samba-client libsmbclient  

yum -y install perl-devel

yum -y install patch
