#!/bin/bash

if [ ! -f rpmforge-release-0.5.3-1.el6.rf.i686.rpm ]; then

  #i386
  wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.i686.rpm

  #x86_64
  #wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

  wget http://dag.wieers.com/rpm/packages/RPM-GPG-KEY.dag.txt
  rpm --import RPM-GPG-KEY.dag.txt

  #i386
  rpm -Uvh rpmforge-release-0.5.3-1.el6.rf.i686.rpm

  #x86_64
  #rpm -Uvh rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

  yum update 
  yum upgrade -y
fi
